name: CI/CD Pipeline Enterprise

on:
  push:
    branches: [ "main" ]

jobs:
  quality-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies frontend
        run: npm ci
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm test
        working-directory: ./frontend

      - name: Install dependencies backend
        run: npm ci
        working-directory: ./backend

      - name: Run Backend Tests
        run: npm test
        working-directory: ./backend